### PR TITLE
Feature/guzzlehttp upgrade

### PR DESCRIPTION
**Pull request by pdscopes**
PHPNessusNG was still using Guzzle ~v3.0, this PR will bring it up to using ~v6.0 (the latest version of Guzzle).

These changes should make no difference to a user of PHPNessusNG except that they will be able to use Guzzle 6 with PHPNessusNG.

### CODE REVIEW

**Comment by leonjza** [comment]
Whoop nice! 👍  
Will test and merge asap.

**Comment by leonjza** [comment]
Have to check, but I think `configureProxy` might be broken with Guzzle 6 (just the way its implemented).

**Comment by pdscopes** [comment]
Do you still think that configureProxy might be broken? I based the changes I made from: http://docs.guzzlephp.org/en/latest/request-options.html#query but don't have a proxy to test it on.

**Comment by leonjza** [comment]
Let me rather test it first before I make more comments :D It might be totally fine.

**Pull request merged**
